"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["app.py"]
DATA_FILES = ["settings.dat"]
OPTIONS = {
    "arch": "universal2",
    "includes": "sqlite3.dump"
}

setup(
    name="SQL Checker",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
